name: wreath_shop_app
description: A wreath shop application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # เปลี่ยนจาก flutter_map 8.1.1 เป็น 6.1.0 ที่รองรับ Dart SDK 3.1.0
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_storage: ^11.2.6
  shared_preferences: ^2.2.1
  image_picker: ^1.0.4
  flutter_image_compress: ^2.0.4
  path_provider: ^2.1.1
  path: ^1.8.3
  provider: ^6.0.5
  url_launcher: ^6.1.14
  flutter_map: ^5.0.0
  latlong2: ^0.9.0
  intl: ^0.18.1
  carousel_slider: ^4.2.1
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  cloudinary_public: ^0.23.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
