// File generated by FlutterFire CLI.
// This file is generated, do not edit manually.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // คุณจะต้องแทนที่ค่าเหล่านี้ด้วยค่าจริงจาก Firebase Console
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB63aq7YwJhslEbp4lbSaU79HdG9PFTxdc',
    appId: '1:1043691980186:web:ea3d68b5c69d8c3d68a623',
    messagingSenderId: '1043691980186',
    projectId: 'reed-thai-project-dti-25',
    authDomain: 'reed-thai-project-dti-25.firebaseapp.com',
    storageBucket: 'reed-thai-project-dti-25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB63aq7YwJhslEbp4lbSaU79HdG9PFTxdc',
    appId: '1:1043691980186:android:4f227286a7194e0b68a623',
    messagingSenderId: '1043691980186',
    projectId: 'reed-thai-project-dti-25',
    storageBucket: 'reed-thai-project-dti-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB63aq7YwJhslEbp4lbSaU79HdG9PFTxdc',
    appId: '1:1043691980186:ios:b2a52cb4ffa739eb68a623',
    messagingSenderId: '1043691980186',
    projectId: 'reed-thai-project-dti-25',
    storageBucket: 'reed-thai-project-dti-25.firebasestorage.app',
    iosClientId: 'my_project_dti_app (ios)',
    iosBundleId: 'com.example.myProjectDtiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB63aq7YwJhslEbp4lbSaU79HdG9PFTxdc',
    appId: '1:1043691980186:ios:b2a52cb4ffa739eb68a623',
    messagingSenderId: '1043691980186',
    projectId: 'reed-thai-project-dti-25',
    storageBucket: 'reed-thai-project-dti-25.firebasestorage.app',
    iosClientId: 'my_project_dti_app (ios)',
    iosBundleId: 'com.example.myProjectDtiApp',
  );
}
